### ISSUE TITLE
Throttle with joystick is only 50% so makes it unable to calibrate

### ISSUE THREAD

**Issue by flyasky** [mavlink/qgroundcontrol#11017]
## Expected Behavior
Able to calibrate joystick.

## Current Behavior
Unable to proceed with calibration because QGC sees just 50% of the axis when I move the throttle fully down.

## Steps to Reproduce:
Please provide an unambiguous set of steps to reproduce the current behavior
1. joystick is Radiomaster zorro controller with EdgeTX latest, model with classic joystick and AETR mixes applied. (it could be calibrated in DRL, Lift-Off with this setup).
2. no settings in ~/.mavlink/joysticks
3. run SITL + QGC
4. load module joystick in mavproxy
5. open QGC > Vehicle Setup/ Joystict Setup, try to calibrate (see attached images)

## System Information
When posting bug reports, include the following information
- Operating System: Ubuntu 22.04
- QGC Version: 4.3.0
- QGC build: stable, appimage
- Flight Controller: just simulation
- Autopilot (with version): Ardupilot Copter 4.5

## Detailed Description

pic1 (maximum, left stick is fully up, see axis2/4)
![image](https://github.com/mavlink/qgroundcontrol/assets/213282/122afcd3-a1dd-44ac-bcc4-2eca13951c82)

pic2 (minimum, left stick is fully down, see axis2/4)
![image](https://github.com/mavlink/qgroundcontrol/assets/213282/b3ef6474-a5ca-41e7-ba9e-5afa79ba5e8b)

**Comment by mtzm** [comment]
I experience the same issue with the FrSky Taranis.

After finding this and this [issue](https://github.com/mavlink/qgroundcontrol/issues/10104), the clues lead to the Game Controller interface of SDL2. After running [jstest-sdl](https://github.com/meleu/jstest-sdl.git) i noticed that the joystick inputs are correct when running `jstest-sdl --test 0`, but wrong when running `jstest-sdl --gamecontroller 0`.
Running `jstest-sdl -l` showed following game controler mapping:
`Mapping: '030068cd09120000544f000011010000,OpenTX FrSky Taranis Joystick,a:b0,b:b1,x:b3,y:b4,back:b10,guide:b12,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,leftx:a0,lefty:a1,rightx:**a3**,righty:**a4**,lefttrigger:**a2**,righttrigger:a5,crc:cd68,platform:Linux'`

Running QGroundControl with the channels rearranged like below solved the issue for me:
`SDL_GAMECONTROLLERCONFIG="030068cd09120000544f000011010000,OpenTX FrSky Taranis Joystick,a:b0,b:b1,x:b3,y:b4,back:b10,guide:b12,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,leftx:a0,lefty:a1,rightx:**a2**,righty:**a3**,lefttrigger:**a4**,righttrigger:a5,crc:cd68,platform:Linux" ./QGroundControl.AppImage`

**Comment by saito1111** [comment]
hi same issue , i forked https://github.com/JacopoPan/aerial-autonomy-stack/ and i modified the docker command to mount  
/dev/input  https://github.com/JacopoPan/aerial-autonomy-stack/blob/main/scripts/docker/Dockerfile.ground 
When i calibrate my controller (radiomaster zorro ) i am blocked on the "push all the throttle down" step .
When i do it only goes to zero on qgc , like i am only able to move from 0 (which correspond to my max down position) and +100 (which correspond to my max up position )

**Comment by kende0211** [comment]
Same error on ubuntu 24.04 lts os.
On  windows, everything works fine.
My remote controller: radiomaster boxer, edge tx.
Remote controller added as HDI device.
Direct connenction, no mavproxy.

Flight Controller: pixhawk
Autopilot: px4

**Comment by DonLakeFlyer** [comment]
Unclear as to whether anyone has tried this on 5.0? Can someone let me know if this repros on 5.0? Anything older than 5.0 is no longer supported.

**Comment by kende0211** [comment]
> Unclear as to whether anyone has tried this on 5.0? Can someone let me know if this repros on 5.0? Anything older than 5.0 is no longer supported.

I have built a few days ago from the git master branch (5.0.8).
Mtzm's fix is okay for me, but it could be better, and I still consider it as an issue.

**Comment by vic-bart** [comment]
I have the exact same issue, using sim_vehicle.py with the EdgeTX Radiomaster Pocket Joystick.

**Comment by DonLakeFlyer** [comment]
Joystick has been reworked in daily builds. You should try that first. The fixes in. daily are not going to go back into stable.

**Comment by fnndyl** [comment]
Can confirm on daily build as of Apr 9 2026 is still an issue. Throttle max is 100, but min maps to 0. On Ubuntu 22.04 with Radiomaster Zorro controller.

**Comment by aerolyticsluis** [comment]
Hello Having this issue with Beta FPV on UBuntu 24. The joystick setting doesn't let me remake the axis either. 
Basicalyl Axis 4 and Axis 5 are flipped.

**Comment by PencilKnot** [comment]
I'm experiencing the same issue with OpenTX TX16SMK3 joystick on the daily build (v5.0.3-1086-g27065dcdd). My throttle joystick is also stuck at 50% so I cannot calibrate it. Has anyone found a fix?

**Comment by DonLakeFlyer** [comment]
> I experience the same issue with the FrSky Taranis.
> 
> After finding this and the issue [#10104](https://github.com/mavlink/qgroundcontrol/issues/10104), the clues lead to the Game Controller interface of SDL2. After running [jstest-sdl](https://github.com/meleu/jstest-sdl.git) i noticed that the joystick inputs are correct when running `jstest-sdl --test 0`, but wrong when running `jstest-sdl --gamecontroller 0`. Running `jstest-sdl -l` showed following game controler mapping: "Mapping: '030068cd09120000544f000011010000,OpenTX FrSky Taranis Joystick,a:b0,b:b1,x:b3,y:b4,back:b10,guide:b12,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,leftx:a0,lefty:a1,rightx:**a3**,righty:**a4**,lefttrigger:**a2**,righttrigger:a5,crc:cd68,platform:Linux'"
> 
> Running QGroundControl with the channels rearranged like below solved the issue for me: "SDL_GAMECONTROLLERCONFIG="030068cd09120000544f000011010000,OpenTX FrSky Taranis Joystick,a:b0,b:b1,x:b3,y:b4,back:b10,guide:b12,start:b11,leftstick:b13,rightstick:b14,leftshoulder:b6,rightshoulder:b7,leftx:a0,lefty:a1,rightx:**a2**,righty:**a3**,lefttrigger:**a4**,righttrigger:a5,crc:cd68,platform:Linux" ./QGroundControl.AppImage"

These sort of problems almost always are because of a joystick which SDL doesn't support out of the box and it requires a custom controller config similar to how the FrSky Taranis was fixed. Unfortunately you'll have to figure out exatly what that looks like yourself.

**Comment by M4rkoHR** [comment]
Still a problem with RadioMaster Pocket on v5.1.4 Ubuntu 26.04 LTS despite jstest showing throttle -32k to +32k just like all other channels, solved with a simple SDL calibration procedure and using the SDL_GAMECONTROLLERCONFIG trick. How do you mess up a CALIBRATION procedure, channels are still there, if 0 is minimum then it's the minimum, don't blame SDL...

**Comment by DonLakeFlyer** [comment]
@M4rkoHR If you don't like the support you are getting then you are welcome to contribute a pull yourself to fix it. Either that or I'll gladly refund your purchase price for QHC.

**Comment by donpurnell** [comment]
I have the same problem with EdgeTX radio controller RadioMaster TX16S, USB connection to Ubuntu 24.04.

@[[Mtzm's fix]( https://github.com/mtzm) ]   does solve the problem, though qGroundControl  v5.1.4  displays a weird re-mapping of channels, that I cannot explain.

For the  TX16S I can run from a terminal:
=================================
export SDL_GAMECONTROLLERCONFIG="<my TX16S UUID>,RadioMaster TX16S,a:b0,b:b1,leftx:a0,lefty:a2,rightx:a3,righty:a1,"

./QGroundControl-x86_64.AppImage
=================================
I extracted <my TX16S UUID>  from
cat /proc/bus/input/devices | grep -E "Name|Sysfs|Handlers"
by converting 4 Raw Hex numbers   to  4 Little-Endian numbers, and concatenating.

 It seems unreasonably difficult, if  an OpenTX  controller on Ubuntu is a moderately common  setup.
