### ISSUE TITLE
Qt6.6.1 Android compile error on windows

### ISSUE THREAD

**Issue by tranhien1612** [mavlink/qgroundcontrol#11169]
I tried successfully with windows version with qt6.6 but when I use android it got an error:
"make: *** No rule to make target 'C:\source\QGC\build-qgroundcontrol-Android_Qt_6_6_2_Clang_arm64_v8a-Debug\ANDROID_PACKAGE_SOURCE_DIR\AndroidManifest.xml', needed by 'libQGroundControl_arm64-v8a.so'.  Stop."

This is a kit information:
![kit](https://github.com/mavlink/qgroundcontrol/assets/69721832/c5e63f3e-dbd4-46b9-a309-8790baf880c0)

And this is the error:
![error](https://github.com/mavlink/qgroundcontrol/assets/69721832/fde0a031-f648-4c50-92c3-244307090a6b)

Please help me solve this problem!

**Comment by HTRamsey** [comment]
kinda weird that it looks like it was running the "which ccache" command on windows. Remove the following code from QGCCommon.pri and try again.
```
# Enable ccache where we can
linux|macx|ios {
    system(which ccache) {
        message("Found ccache, enabling")
        !ios {
            QMAKE_CXX = ccache $$QMAKE_CXX
            QMAKE_CC  = ccache $$QMAKE_CC
        } else {
            QMAKE_CXX = $$PWD/tools/iosccachecc.sh
            QMAKE_CC  = $$PWD/tools/iosccachecxx.sh
        }
    }
}
```

**Comment by anhhien2k** [comment]
@HTRamsey I tried your suggestion but the error still occurs. I am building for android and i think what you said is not the problem here.

**Comment by andrefreitas97** [comment]
I had the same problem. Edit the AndroidManifest.xml file as you want (name of the app... etc) and then copy all the files in qgroundcontrol
/android folder to the C:\source\QGC\build-qgroundcontrol-Android_Qt_6_6_2_Clang_arm64_v8a-Debug\ANDROID_PACKAGE_SOURCE_DIR folder and it should work

**Comment by anhhien2k** [comment]
@andrefreitas97 This is the error:
make: *** No rule to make target 'C:\source\QGC\build-qgroundcontrol-Android_Qt_6_6_1_Clang_arm64_v8a-Debug\ANDROID_PACKAGE_SOURCE_DIR\AndroidManifest.xml', needed by 'libQGroundControl_arm64-v8a.so'.  Stop.
The process "C:\Install\Android\Sdk\ndk\25.1.8937393\prebuilt\windows-x86_64\bin\make.exe" exited with code 2.
Error while building/deploying project qgroundcontrol (kit: Android Qt 6.6.1 Clang arm64-v8a)
When executing step "Make"

There are 2 folder in build-qgroundcontrol-Android_Qt_6_6_1_Clang_arm64_v8a-Debug: 
- .qm
- .qtc_clangd
 
I don't know the ANDROID_PACKAGE_SOURCE_DIR  folder?

**Comment by anhhien2k** [comment]
@andrefreitas97 I followed your instructions and it worked. However, it shows another error related to UnitTest:

```
C:\source\QGC\qgroundcontrol\src\main.cc:386:28: error: use of undeclared identifier 'UnitTest'
            int failures = UnitTest::run(unitTestOptions);
```

I tried changing it to OFF in the `CMakeList.txt` file:
```
cmake_dependent_option(QGC_BUILD_TESTING "Enable testing" OFF "CMAKE_BUILD_TYPE STREQUAL Debug" OFF)
```
but this error still occurs.

pls help me to solve this problem!

**Comment by HTRamsey** [comment]
This is fixed in #11154 (unit tests originally weren't meant for mobile). Just build via qmake until cmake is ready.

**Comment by anhhien2k** [comment]
@HTRamsey  I followed your instructions and it shows another error:
```
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\ScreenTools\ScreenTools.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\ClickableColor.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\DeadMouseArea.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\ParameterEditor.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\JoystickThumbPad.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\GPSIndicatorPage.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\MissionItemStatus.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\FactSliderPanel.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\OfflineMapButton.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\TerrainStatus.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCMenuSeparator.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCMapCircleVisuals.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\SubMenuButton.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCColoredImage.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCMenu.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\MissionItemIndexLabel.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\MissionItemMapVisual.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCLabel.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\ToolIndicatorPage.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\LabelledComboBox.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\FlightModeDropdown.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCTextField.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\MainWindowSavedState.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\PipView.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\AppMessages.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\LogReplayStatusBar.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\FlightModeMenuIndicator.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\ExclusiveGroupItem.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\FactSlider.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\InstrumentValueLabel.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\OfflineMapEditor.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCSlider.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCRoundButton.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\FileButton.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\SettingsGroupLayout.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\InstrumentValueEditDialog.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\PIDTuning.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCToolInsets.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\VehicleSummaryRow.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\MAVLinkChart.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\CameraSection.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\LabelledButton.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\CameraCalcCamera.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\OfflineMapInfo.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCMenuItem.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\SimpleItemMapVisuals.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCFileDialog.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCSwitch.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\KMLOrSHPFileDialog.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\AltModeDialog.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\BatteryIndicatorContentItem.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\HorizontalFactValueGrid.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCPopupDialog.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\SignalStrength.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\SliderSwitch.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\AxisMonitor.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\AutotuneUI.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCMovableItem.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\SetupPage.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\RCChannelMonitor.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\IndicatorButton.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\CameraCalcGrid.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\BatteryIndicator.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\SurveyMapVisuals.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\ToolStrip.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\MainStatusIndicatorOfflinePage.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCFlickable.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\FlightModeIndicator.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\DropPanel.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCComboBox.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\TransectStyleComplexItemStats.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\HackFileDialog.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCTabButton.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\GeoFenceMapVisuals.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\PreFlightCheckModel.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCMouseArea.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCSimpleMessageDialog.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\APMSubMotorDisplay.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCDynamicObjectManager.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\DropButton.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\MAVLinkMessageButton.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCMapLabel.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\PlanEditToolbar.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCListView.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\ContentAreaCalc.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\FirstRunPrompt.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\ToolStripHoverButton.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCMapPolygonVisuals.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\TransectStyleComplexItemEditor.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCCheckBoxSlider.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCGroupBox.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCOptionsComboBox.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\HeightIndicator.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\SelectableControl.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCColumnButton.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCButton.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\TransectStyleComplexItemTabBar.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\ModeSwitchDisplay.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\RallyPointMapVisuals.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCMapPolylineVisuals.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\LabelledLabel.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCCheckBox.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCToolBarButton.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCMarqueeLabel.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\EditPositionDialog.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\MainStatusIndicator.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\MissionCommandDialog.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCTabBar.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\SectionHeader.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\VehicleRotationCal.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\RallyPointItemEditor.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\QGCRadioButton.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\TransectStyleMapVisuals.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\PipState.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\AnalyzePage.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\ParameterEditorDialog.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\TransectStyleComplexItemTerrainFollow.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\MultiRotorMotorDisplay.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\ParameterDiffDialog.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\RCToParamDialog.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\InstrumentValueValue.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\GeoFenceEditor.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\PreFlightCheckButton.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\MissionItemEditor.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\RallyPointEditorHeader.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\PreFlightCheckGroup.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\Controls\FlightModeMenu.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\MissionItemIndicator.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\PolygonEditor.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\CustomMapItems.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\FlightMap.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\CenterMapDropPanel.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\MissionItemView.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\PhotoVideoControl.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\MissionItemIndicatorDrag.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\CompassHeadingIndicator.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\QGCAttitudeWidget.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\MapScale.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\MissionLineView.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\SplitIndicator.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\CompassDial.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\QGCCompassWidget.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\MapFitFunctions.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\QGCAttitudeHUD.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\QGCPitchIndicator.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\ProximityRadarMapView.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\PlanMapItems.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\MapLineArrow.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\VehicleMapItem.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\QGCVideoBackground.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\QGCArtificialHorizon.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\CameraTriggerIndicator.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightMap\CenterMapDropButton.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FactControls\FactTextFieldGrid.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FactControls\FactCheckBoxSlider.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FactControls\LabelledFactTextField.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FactControls\FactBitmask.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FactControls\LabelledFactSlider.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FactControls\FactLabel.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FactControls\FactComboBox.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FactControls\FactCheckBox.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FactControls\FactTextField.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FactControls\FactValueSlider.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FactControls\FactTextFieldSlider.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FactControls\FactTextFieldRow.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FactControls\LabelledFactComboBox.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FactControls\AltitudeFactTextField.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\PX4\BatteryParams.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\PX4\SensorSetupPage.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\ObstacleDistanceOverlay.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\GuidedActionPause.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\GripperMenu.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\FlyViewToolBarIndicators.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\TerrainProgress.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\PreFlightSensorsHealthCheck.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\GuidedActionRTL.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\FlyViewWidgetLayer.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\ProximityRadarVideoView.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\ProximityRadarValues.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\FlyViewToolStrip.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\FlyViewBottomRightRowLayout.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\FlyView.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\VehicleWarnings.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\FlyViewTopRightColumnLayout.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\GuidedActionActionList.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\GuidedActionConfirm.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\FlyViewInsetViewer.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\GuidedToolStripAction.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\PreFlightRCCheck.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\PreFlightBatteryCheck.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\ObstacleDistanceOverlayVideo.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\FlyViewToolStripActionList.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\GuidedActionGripper.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\TelemetryValuesBar.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\MultiVehicleList.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\FlyViewCustomLayer.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\PreFlightSoundCheck.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\FlyViewInstrumentPanel.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\FlyViewMissionCompleteDialog.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\FlyViewMap.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\FlyViewToolBar.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\GuidedActionsController.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\FlyViewVideo.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\GuidedActionLand.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\GuidedActionTakeoff.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\ObstacleDistanceOverlayMap.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\FlyViewPreFlightChecklistPopup.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\GuidedActionList.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\PreFlightGPSCheck.qml:The system cannot find the file specified.
Cannot open input file C:\source\qgroundcontrol\src\QmlControls\QGroundControl\FlightDisplay\GuidedValueSlider.qml:The system cannot find the file specified.
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.Windows
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.macOS
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.iOS
Warning: QML import could not be resolved in any of the import paths: QGroundControl.Palette
Warning: QML import could not be resolved in any of the import paths: Custom.Widgets
Warning: QML import could not be resolved in any of the import paths: QtQuick.Controls.Styles
Warning: QML import could not be resolved in any of the import paths: org.freedesktop.gstreamer.GLVideoItem
Warning: QML import could not be resolved in any of the import paths: QGroundControl.Controllers
Warning: QML import could not be resolved in any of the import paths: QGroundControl.SettingsManager
Warning: QML import could not be resolved in any of the import paths: QGroundControl.ArduPilot
Warning: QML import could not be resolved in any of the import paths: QGroundControl.QGCPositionManager
Warning: QML import could not be resolved in any of the import paths: QGroundControl.MultiVehicleManager
Warning: QML import could not be resolved in any of the import paths: MAVLink
Warning: QML import could not be resolved in any of the import paths: Viewer3D
Warning: QML import could not be resolved in any of the import paths: SiYi.Object
Warning: QML import could not be resolved in any of the import paths: QGroundControl.ShapeFileHelper
Warning: QML import could not be resolved in any of the import paths: QGroundControl.UTMSP
Warning: QML import could not be resolved in any of the import paths: QtQuick.Extras
Warning: QML import could not be resolved in any of the import paths: QGroundControl.Templates
Warning: QML import could not be resolved in any of the import paths: QGroundControl.ScreenToolsController
Warning: QML import could not be resolved in any of the import paths: QGroundControl.QGCMapEngineManager
Warning: QML import could not be resolved in any of the import paths: QGroundControl.AutoPilotPlugin
Warning: QML import could not be resolved in any of the import paths: QGroundControl.Viewer3D
Warning: QML import could not be resolved in any of the import paths: Viewer3D.Models3D
Warning: QML import could not be resolved in any of the import paths: Viewer3D.Models3D.Drones
Failed to copy C:/source/build-qgroundcontrol-Android_Qt_6_6_1_Clang_arm64_v8a-Debug/android-build/AndroidManifest.xml to C:/source/build-qgroundcontrol-Android_Qt_6_6_1_Clang_arm64_v8a-Debug/android-build/AndroidManifest.xml.
12:27:43: The process "C:\Qt\6.6.1\mingw_64\bin\androiddeployqt.exe" exited with code 11.
Error while building/deploying project qgroundcontrol (kit: Android Qt 6.6.1 Clang arm64-v8a)
```
pls help me to solve this problem!

**Comment by VijaySue** [comment]
> This is fixed in #11154 (unit tests originally weren't meant for mobile). Just build via qmake until cmake is ready.

I get the same error with qmake, and still can't build in cmake. Is this issue not fixed?

![1709729983827](https://github.com/mavlink/qgroundcontrol/assets/101463820/924a3d28-5ddd-476e-8b93-38a5c737f9eb)

**Comment by anhhien2k** [comment]
@VijaySue With this error, you follow some steps:
- create ANDROID_PACKAGE_SOURCE_DIR folder in E:\QtProject\build-qgroundcontrol-Android_Qt_6_6_2_Clang_arm64_v8a-Debug.
- After, you copy all the files in qgroundcontrol/android folder to the E:\QtProject\build-qgroundcontrol-Android_Qt_6_6_2_Clang_arm64_v8a-Debug\ANDROID_PACKAGE_SOURCE_DIR folder and build again.

**Comment by Zameer-fatima** [comment]
Heyy!!
I am facing the same errors as you have. How to solve this. can you pls help me

**Comment by VijaySue** [comment]
With this error, you follow some steps:

create ANDROID_PACKAGE_SOURCE_DIR folder in E:\QtProject\build-qgroundcontrol-Android_Qt_6_6_2_Clang_arm64_v8a-Debug.
After, you copy all the files in qgroundcontrol/android folder to the E:\QtProject\build-qgroundcontrol-Android_Qt_6_6_2_Clang_arm64_v8a-Debug\ANDROID_PACKAGE_SOURCE_DIR folder and build again.






---- Replied Message ----
| From | Zameer ***@***.***> |
| Date | 3/13/2024 14:06 |
| To | ***@***.***> |
| Cc | ***@***.***>,
***@***.***> |
| Subject | Re: [mavlink/qgroundcontrol] Qt6.6.1 Android compile error on windows (Issue #11169) |

Heyy!!
I am facing the same errors as you have. How to solve this. can you pls help me

**Comment by Zameer-fatima** [comment]
@VijaySue 
Hii !!
Thanks for your response & suggestion, It worked and that errors were gone But it is still showing the error I have mentioned below.
How to solve this one??, pls guide...

But at last the Build Successfull is displaying and it has errors with emulator.

![image](https://github.com/mavlink/qgroundcontrol/assets/89373003/eb0ce1bb-23ff-4847-9aaf-d6d91e43d385)

![image](https://github.com/mavlink/qgroundcontrol/assets/89373003/a053697e-ef8b-4b12-ac82-f4ce7205bcf1)

**Comment by VijaySue** [comment]
You should use Android clang compiler instead of mingw.



---- Replied Message ----
| From | Zameer ***@***.***> |
| Date | 03/15/2024 21:19 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [mavlink/qgroundcontrol] Qt6.6.1 Android compile error on windows (Issue #11169) |

@VijaySue
Hii !!
Thanks for your response & suggestion, It worked and that errors were gone But it is still showing the error I have mentioned below.
How to solve this one??, pls guide...

But at last the Build Successfull is displaying and it has errors with emulator.

image.png (view on web)

image.png (view on web)

**Comment by tranhien1612** [comment]
@VijaySue Did you build successfully?

**Comment by VijaySue** [comment]
Can your emulater start directly? Other than start by run project.



---- Replied Message ----
| From | Zameer ***@***.***> |
| Date | 03/15/2024 21:19 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [mavlink/qgroundcontrol] Qt6.6.1 Android compile error on windows (Issue #11169) |

@VijaySue
Hii !!
Thanks for your response & suggestion, It worked and that errors were gone But it is still showing the error I have mentioned below.
How to solve this one??, pls guide...

But at last the Build Successfull is displaying and it has errors with emulator.

image.png (view on web)

image.png (view on web)

**Comment by VijaySue** [comment]
Yes.



---- Replied Message ----
| From | Trần Bá ***@***.***> |
| Date | 03/16/2024 00:26 |
| To | ***@***.***> |
| Cc | ***@***.***>***@***.***> |
| Subject | Re: [mavlink/qgroundcontrol] Qt6.6.1 Android compile error on windows (Issue #11169) |

@VijaySue Did you build successfully?

**Comment by ZHCLN** [comment]
> I tried successfully with windows version with qt6.6 but when I use android it got an error: "make: *** No rule to make target 'C:\source\QGC\build-qgroundcontrol-Android_Qt_6_6_2_Clang_arm64_v8a-Debug\ANDROID_PACKAGE_SOURCE_DIR\AndroidManifest.xml', needed by 'libQGroundControl_arm64-v8a.so'. Stop."
> 
> This is a kit information: ![kit](https://private-user-images.githubusercontent.com/69721832/309237810-c5e63f3e-dbd4-46b9-a309-8790baf880c0.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzA0NTIsIm5iZiI6MTcxMDczMDE1MiwicGF0aCI6Ii82OTcyMTgzMi8zMDkyMzc4MTAtYzVlNjNmM2UtZGJkNC00NmI5LWEzMDktODc5MGJhZjg4MGMwLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDAyNDkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWNhODgxMmFmNTZkZDE1OTM5MDA1MTQ3Mjk4YThkNGQ5ZDcxMzNjNDQwMzhhOTY0MDdiYzlkOTgyMWRiYTlhZDImWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.4LFdjOGhnZA9nkcxYnIXicfOZP1fqQeyEAn04Dls6iM)
> 
> And this is the error: ![error](https://private-user-images.githubusercontent.com/69721832/309237939-fde0a031-f648-4c50-92c3-244307090a6b.PNG?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTA3MzA0NTIsIm5iZiI6MTcxMDczMDE1MiwicGF0aCI6Ii82OTcyMTgzMi8zMDkyMzc5MzktZmRlMGEwMzEtZjY0OC00YzUwLTkyYzMtMjQ0MzA3MDkwYTZiLlBORz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDAzMTglMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwMzE4VDAyNDkxMlomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTIzYTI5MGNhMjE4NzcxYWJmOGI2NjJhNWQyOWYwNDJjNTBhZWVlNDQyNmI1MDBkMjUxMjZjNmI2YjIzMjVjOTEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.7THFB6zM41WsRJbjR67jd7XpQYf4j2CrB2MK0PKhnT4)
> 
> Please help me solve this problem!

I also encountered the same problem, have you solved it now?

**Comment by tranhien1612** [comment]
> @VijaySue With this error, you follow some steps:
> 
> * create ANDROID_PACKAGE_SOURCE_DIR folder in E:\QtProject\build-qgroundcontrol-Android_Qt_6_6_2_Clang_arm64_v8a-Debug.
> * After, you copy all the files in qgroundcontrol/android folder to the E:\QtProject\build-qgroundcontrol-Android_Qt_6_6_2_Clang_arm64_v8a-Debug\ANDROID_PACKAGE_SOURCE_DIR folder and build again.

@ZHCLN pls try it

**Comment by ZHCLN** [comment]
> > @VijaySue With this error, you follow some steps:
> > 
> > * create ANDROID_PACKAGE_SOURCE_DIR folder in E:\QtProject\build-qgroundcontrol-Android_Qt_6_6_2_Clang_arm64_v8a-Debug.
> > * After, you copy all the files in qgroundcontrol/android folder to the E:\QtProject\build-qgroundcontrol-Android_Qt_6_6_2_Clang_arm64_v8a-Debug\ANDROID_PACKAGE_SOURCE_DIR folder and build again.
> 
> @ZHCLN pls try it

I tried your solution, but I still get other errors.
<img width="754" alt="微信图片_20240331175122" src="https://github.com/mavlink/qgroundcontrol/assets/114682814/aa12922f-0a08-47b1-b1a7-b93735ceab05">

<img width="788" alt="微信图片_20240331174956" src="https://github.com/mavlink/qgroundcontrol/assets/114682814/9f2c3278-f2cc-49cf-ae94-a7bfdf0efb3c">

**Comment by Zameer-fatima** [comment]
> Can your emulater start directly? Other than start by run project.
> […](#)
> ---- Replied Message ---- | From | Zameer ***@***.***> | | Date | 03/15/2024 21:19 | | To | ***@***.***> | | Cc | ***@***.***>***@***.***> | | Subject | Re: [mavlink/qgroundcontrol] Qt6.6.1 Android compile error on windows (Issue #11169) | @VijaySue Hii !! Thanks for your response & suggestion, It worked and that errors were gone But it is still showing the error I have mentioned below. How to solve this one??, pls guide... But at last the Build Successfull is displaying and it has errors with emulator. image.png (view on web) image.png (view on web) — Reply to this email directly, view it on GitHub, or unsubscribe. You are receiving this because you were mentioned.Message ID: ***@***.***>

I have used physical device. The apk worked in my device. Thank You

**Comment by Zameer-fatima** [comment]
@VijaySue
Hii !
Thank you for your suggestions, but now
I aim to develop QGroundControl (QGC) for Android using QT5.15.1, specifically targeting stable version 4.3.0. However, I'm encountering an issue where the arm64_v8a kit is not available in QT5, leading to difficulties in the building process. Could you please advise on how to successfully build it using QT5?

**Comment by BreederBai** [comment]
@ZHCLN I also encountered the same error as you. Have you solved this error?
![image](https://github.com/mavlink/qgroundcontrol/assets/27894314/a8e8ec50-7765-44e8-84e5-e29d9fcf5184)
