### ISSUE TITLE
QGC is unable to find SYS_HAS_NUM_ASPD parameter on PX4 (1.14.3)

### ISSUE THREAD

**Issue by trileis** [mavlink/qgroundcontrol#11882]
## Expected Behavior
No error displayed after firmware upgrade

## Current Behavior
A `SYS_HAS_NUM_ASPD` missing parameter is thrown (see screenshot in reproducer)

## Steps to Reproduce:
With "Fixed Wing" airbone,
1. Flash FC with latest firmware version (1.14.3): 
![367262594-4ee7a388-0a5e-49f6-936c-feec7d8273b8](https://github.com/user-attachments/assets/b26cc712-fe49-434c-827e-3f63a85c1ddb)

2. Go back to summary and get a popup with the error: 
![367262589-0f2a64fc-10e3-4ca8-85a5-92350207c166](https://github.com/user-attachments/assets/0160d647-1e18-4238-9843-4be99ccac711)

## System Information
- Operating System: Windows10
- QGC Version: 4.4.2/4.4.1
- QGC build: stable
- Flight Controller: Pixhawk 6X
- Autopilot (with version): PX4 1.14.3

## Detailed Description
Apparently the parameter SYS_HAS_NUM_ASPD is not present on the PX4 version 1.14.3, it should be merged in 1.15.0 (beta). In QGC code diff between version 4.4.0 -> 4.4.1 ([here](https://github.com/mavlink/qgroundcontrol/compare/v4.4.0...v4.4.1#diff-9c83171468cf135766163fce20c29d00cb6f45f6ed4b90459c311a40919f4c25)), this parameter is searched when PX4 version is upper or equal to 1.14. It should better be 1.15.

**Comment by DonLakeFlyer** [comment]
Fixed in daily builds

**Comment by trileis** [comment]
I don't see any modification on that part of code ((PX4/SensorComponents.cc)[src/AutoPilotPlugins/PX4/SensorsComponent.cc]) on master since commit: da57ee. I think the problem still there on daily build.

**Comment by DonLakeFlyer** [comment]
> I think the problem still there on daily build.

And you actually ran the daily build to verify that?

**Comment by DonLakeFlyer** [comment]
https://github.com/mavlink/qgroundcontrol/pull/11425

**Comment by trileis** [comment]
Yes, I ran it two days before with the last master release. I think while PX4 doesn't release (at the moment) the parameter `SYS_HAS_NUM_ASPD`, this couldn't work. The `SYS_HAS_NUM_ASPD`  parameter will be part of PX4 v1.15.0, which is at the moment in beta test.

To fix it, I downgrade QGC to 4.4.0 and it works like a charm with PX4 v1.4.3.

I'm supose the [#11425](https://github.com/mavlink/qgroundcontrol/pull/11425) has been release too late. A possible fix could be to modify src/AutoPilotPlugins/PX4/SensorsComponent.cc to replace the check on PX4 version v1.14 by a check on v1.15.

I would have the time to do that as a dev but I'm trying to make my plane flying. I'm just playing with the Pixhawk system since a week so I'm not a dev at that time.

**Comment by DonLakeFlyer** [comment]
> there's possibly a bug

Yup, I'll fix it

**Comment by DonLakeFlyer** [comment]
Can you pull the build artifact from this pull once it's done and verify that it works for you?

**Comment by trileis** [comment]
Nice, I'll test that.

**Comment by trileis** [comment]
I tested the artifact from pull request (v4.3.0-889-gece5b6e55) and the problem is fixed. Thanks.

**Comment by DonLakeFlyer** [comment]
Great, thanks so much for testing. Sorry for screwing this up.
