### ISSUE TITLE
Incorrect UDP link causing multiple "Warning a second system is using system id (247)" popup boxes

### ISSUE THREAD

**Issue by ggregory8** [mavlink/qgroundcontrol#1261]
As mentioned on gitter. If I enter incorrect UDP link for target host and it detects its own (QGC) system ID it creates the MAVLink Protocol popup box with message "Warning a second system is using system id (247)". If you do not close this box within ~1s another one will popup over top. They will continuously open. If you manage to quickly click 'ok' on a couple of popups then they will stop opening new popups.

Steps to reproduce:
1. Use master QGC from 2015/02/22 (v2.3.0)
2. Add new Communication Link with this following settings:
Link Type: UDP
Listening Port: 14550
Add Target Host: localhost:14550         i.e (127.0.0.1:14550)
3. Click Connect

Note that the default target port used to be 14555, now it uses 14550 which is the same as the default listening port. Having these two the same causes the duplicate system ID detection.

Using the stable release (v2.2.1) on windows, following the same steps, generates the same popup, but only once as it should.

**Comment by ggregory8** [comment]
![qgc_system_id_error](https://cloud.githubusercontent.com/assets/5005893/6321157/7d6b1690-bb2e-11e4-9a98-e5a3ace153b3.png)

**Comment by DonLakeFlyer** [comment]
@dogmaphobic Gus can you take a look at this? I think it's just a typo in QGC_UDP_PORT but want to make sure there wasn't a reason for the change. Also probably a good idea it verify the host and listening port are not the same.

**Comment by dogmaphobic** [comment]
The original code, before I changed to LinkConfiguration had the default port set to 14550. I just used what I found there:

```c++
    UDPLink(QHostAddress host = QHostAddress::Any, quint16 port = 14550);
```

Should I change the default to 14555? I will take a look at not allowing a host:port conflict.

**Comment by DonLakeFlyer** [comment]
Config code did this though:
-    QString hostName = QInputDialog::getText(this, tr("Add a new IP address / hostname to MAVLink"),
-                       tr("Host (hostname:port):"), QLineEdit::Normal,
-                       "localhost:14555", &ok);
-    if (ok && !hostName.isEmpty())
-        link->addHost(hostName);

I'm not familiar with UDP but seem like from the above it should be 14555.

**Comment by dogmaphobic** [comment]
Found it. The error is in the Add Host logic, which is using the same port for targets.

**Comment by dogmaphobic** [comment]
Yep :)

**Comment by dogmaphobic** [comment]
Pushed in #1265

**Comment by DonLakeFlyer** [comment]
Fixed

**Comment by ggregory8** [comment]
@DonLakeFlyer I have just pulled master and recompiled. The default target port has changed to 14555 which is good, but the multiple popups is still occurring on 'incorrect' settings of target host.

This is occurring during the same procedure I mentioned above i.e UDP target of 127.0.0.1:14550

**Comment by dogmaphobic** [comment]
My fix was specific to the wrong default port. It was a safe and isolated fix. The multiple dialog pop ups is a different problem. I don't have anything that connects through UDP to test this.

**Comment by ggregory8** [comment]
I can reproduce this problem simply by following the steps in post 1. You don't need any UDP connections. The problem exists if trying to connect to 'yourself'.

**Comment by DonLakeFlyer** [comment]
The host and listening port need to verified that they aren't the same.
