### ISSUE TITLE
Missing Imports when Building Sstable_V5 for Android

### ISSUE THREAD

**Issue by NoelCav** [mavlink/qgroundcontrol#13375]
### Have you checked the latest release for fixes?

- [x] Yes, I’ve tested on the latest release

### Description

**Expected Behavior**
When I compile QGC Stable V5.0 Branch, it should run without error.

**Current Behavior**
When compiling, I get an error that claims that all of the imports in "/qml" prefix of qgroundcontrol.qrc are nonexistent, and seems to be checking for them in the incorrect place.

**Steps To Reproduce**
1. Clone QGC branch Stable_V5.0
2. Run Android compilation

**Additional Details**
The build completes but the APK is broken and QGC will crash on start.

### System Information

QGC Version: Stable 5.0 Branch
Operating System: Ubuntu 24

### Log Files and Screenshots

<img width="2401" height="1346" alt="Image" src="https://github.com/user-attachments/assets/bca28e21-0f3a-48ac-8268-0ee437455861" />

<img width="2294" height="1636" alt="Image" src="https://github.com/user-attachments/assets/81fa0fa7-3227-48c2-ba80-7b76f3d4100d" />

**Comment by HTRamsey** [comment]
Think this is fixed in daily but just hasn't been backported

**Comment by DonLakeFlyer** [comment]
@NoelCav Does the Stable 5.0 APK from here work for you: https://docs.qgroundcontrol.com/master/en/qgc-user-guide/getting_started/download_and_install.html?

**Comment by NoelCav** [comment]
The version available to download at your link works on my device (Skydroid G20). 

I switched to the Master branch and the build completed without error, but still crashed when starting on my device.

Is there any other options that might be causing this issue?
Using:
Java 1.17
NDK 26.1.19
Android Build tools 35

**Comment by DonLakeFlyer** [comment]
What version of Android is running on the G20?

**Comment by NoelCav** [comment]
Android 13. But I assume the issue is related to my build environment since the release apk you sent works fine.

**Comment by DonLakeFlyer** [comment]
You are going to need to debug this using either `adb logcat` or a real debugger to see why it is crashing
