### ISSUE TITLE
QGC Crashes when disconnecting USB from flight controller

### ISSUE THREAD

**Issue by nathanvs-spsa** [mavlink/qgroundcontrol#13449]
### Have you checked the latest release for fixes?

- [x] Yes, I’ve tested on the latest release

### Description

**Expected Behavior**
QGC should disconnect and show 'disconnected' as the status (but the application stay open).

**Current Behavior**
If a flight controller is connected and the USB is pulled out, QGC crashes and closes.

**Steps To Reproduce**
1. Open QGC
2. Plug in Flight Controller
3. Wait for connection
4. Disconnect USB
5. QGC Crashes

### System Information

QGC Version: V5.0.7 (Issue DOES NOT occur on V5.0)
QGC build: Stable
Operating System: Ubuntu 24.04.3 LTS
Flight Controller: CubePilot Cube Orange +
Autopilot Software (with version): Forked version of PX4 v1.15.3

### Log Files and Screenshots
I can't seem to upload the log txt file - Output below.

`<pre>40.273 - debug: void VehicleLinkManager::_linkDisconnected() linkCount 1 (VehicleLog:unknown:0)
    40.274 - debug: All links removed. Closing down Vehicle. (VehicleLog:unknown:0)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:36: TypeError: Cannot read property &apos;currentCameraInstance&apos; of null (default:unknown:36)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:88: TypeError: Cannot read property &apos;cameras&apos; of null (default:unknown:88)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:36: TypeError: Cannot read property &apos;currentCameraInstance&apos; of null (default:unknown:36)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:88: TypeError: Cannot read property &apos;cameras&apos; of null (default:unknown:88)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:267: TypeError: Cannot read property &apos;trackingEnabled&apos; of null (default:unknown:267)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:252: TypeError: Cannot read property &apos;batteryRemainingStr&apos; of null (default:unknown:252)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:254: TypeError: Cannot read property &apos;batteryRemaining&apos; of null (default:unknown:254)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:245: TypeError: Cannot read property &apos;storageFreeStr&apos; of null (default:unknown:245)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:247: TypeError: Cannot read property &apos;storageStatus&apos; of null (default:unknown:247)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:37: TypeError: Cannot read property &apos;cameraMode&apos; of null (default:unknown:37)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:39: TypeError: Cannot read property &apos;videoCaptureStatus&apos; of null (default:unknown:39)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:181: TypeError: Cannot read property &apos;videoCaptureStatus&apos; of null (default:unknown:181)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:98: TypeError: Cannot read property &apos;hasModes&apos; of null (default:unknown:98)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:87: TypeError: Cannot read property &apos;modelName&apos; of null (default:unknown:87)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:72: TypeError: Cannot read property &apos;zoomLevel&apos; of null (default:unknown:72)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:58: TypeError: Cannot read property &apos;hasZoom&apos; of null (default:unknown:58)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:30: TypeError: Cannot read property &apos;capturesVideo&apos; of null (default:unknown:30)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:40: TypeError: Cannot read property &apos;photoCaptureStatus&apos; of null (default:unknown:40)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:41: TypeError: Cannot read property &apos;photoCaptureStatus&apos; of null (default:unknown:41)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:267: TypeError: Cannot read property &apos;trackingEnabled&apos; of null (default:unknown:267)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:252: TypeError: Cannot read property &apos;batteryRemainingStr&apos; of null (default:unknown:252)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:254: TypeError: Cannot read property &apos;batteryRemaining&apos; of null (default:unknown:254)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:245: TypeError: Cannot read property &apos;storageFreeStr&apos; of null (default:unknown:245)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:247: TypeError: Cannot read property &apos;storageStatus&apos; of null (default:unknown:247)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:37: TypeError: Cannot read property &apos;cameraMode&apos; of null (default:unknown:37)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:39: TypeError: Cannot read property &apos;videoCaptureStatus&apos; of null (default:unknown:39)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:181: TypeError: Cannot read property &apos;videoCaptureStatus&apos; of null (default:unknown:181)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:98: TypeError: Cannot read property &apos;hasModes&apos; of null (default:unknown:98)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:87: TypeError: Cannot read property &apos;modelName&apos; of null (default:unknown:87)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:72: TypeError: Cannot read property &apos;zoomLevel&apos; of null (default:unknown:72)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:58: TypeError: Cannot read property &apos;hasZoom&apos; of null (default:unknown:58)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:30: TypeError: Cannot read property &apos;capturesVideo&apos; of null (default:unknown:30)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:40: TypeError: Cannot read property &apos;photoCaptureStatus&apos; of null (default:unknown:40)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:41: TypeError: Cannot read property &apos;photoCaptureStatus&apos; of null (default:unknown:41)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:36: TypeError: Cannot read property &apos;currentCameraInstance&apos; of null (default:unknown:36)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:88: TypeError: Cannot read property &apos;cameras&apos; of null (default:unknown:88)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:36: TypeError: Cannot read property &apos;currentCameraInstance&apos; of null (default:unknown:36)
    40.275 - warning: qrc:/qml/QGroundControl/FlightMap/Widgets/PhotoVideoControl.qml:88: TypeError: Cannot read property &apos;cameras&apos; of null (default:unknown:88)
    40.275 - debug: ~Vehicle Vehicle(0x5a18bee3d730) (VehicleLog:unknown:0)
    40.275 - debug: First call to begindResetModel - calling QAbstractListModel::beginResetModel QmlObjectListModel(0x5a18bcd703d0) (QmlObjectListModelLog:unknown:0)
    40.275 - debug: _resetModelNestingCount: 1 QmlObjectListModel(0x5a18bcd703d0) (QmlObjectListModelLog:unknown:0)
    40.275 - debug: _resetModelNestingCount: 0 QmlObjectListModel(0x5a18bcd703d0) (QmlObjectListModelLog:unknown:0)
    40.275 - debug: Last call to endResetModel - calling QAbstractListModel::endResetModel QmlObjectListModel(0x5a18bcd703d0) (QmlObjectListModelLog:unknown:0)
    40.276 - debug: First call to begindResetModel - calling QAbstractListModel::beginResetModel QmlObjectListModel(0x5a18bee6fe60) (QmlObjectListModelLog:unknown:0)
    40.276 - debug: _resetModelNestingCount: 1 QmlObjectListModel(0x5a18bee6fe60) (QmlObjectListModelLog:unknown:0)
    40.276 - debug: _resetModelNestingCount: 0 QmlObjectListModel(0x5a18bee6fe60) (QmlObjectListModelLog:unknown:0)
    40.276 - debug: Last call to endResetModel - calling QAbstractListModel::endResetModel QmlObjectListModel(0x5a18bee6fe60) (QmlObjectListModelLog:unknown:0)
    40.303 - debug: First call to begindResetModel - calling QAbstractListModel::beginResetModel QmlObjectListModel(0x5a18b7281200) (QmlObjectListModelLog:unknown:0)
    40.303 - debug: _resetModelNestingCount: 1 QmlObjectListModel(0x5a18b7281200) (QmlObjectListModelLog:unknown:0)
    40.303 - debug: _resetModelNestingCount: 0 QmlObjectListModel(0x5a18b7281200) (QmlObjectListModelLog:unknown:0)
    40.303 - debug: Last call to endResetModel - calling QAbstractListModel::endResetModel QmlObjectListModel(0x5a18b7281200) (QmlObjectListModelLog:unknown:0)
    40.305 - debug: _activeVehicleChanged QObject(0x0) (PlanMasterControllerLog:unknown:0)
    40.305 - debug: setCurrentPlanViewSeqNum (MissionControllerLog:unknown:0)
    40.305 - debug: _activeVehicleChanged: Plan View - Previous clean plan exists, no new active vehicle, clear stale plan (PlanMasterControllerLog:unknown:0)
    40.305 - debug: First call to begindResetModel - calling QAbstractListModel::beginResetModel QmlObjectListModel(0x5a18b7491cd0) (QmlObjectListModelLog:unknown:0)
    40.305 - debug: _resetModelNestingCount: 1 QmlObjectListModel(0x5a18b7491cd0) (QmlObjectListModelLog:unknown:0)
    40.305 - debug: _resetModelNestingCount: 0 QmlObjectListModel(0x5a18b7491cd0) (QmlObjectListModelLog:unknown:0)
    40.305 - debug: Last call to endResetModel - calling QAbstractListModel::endResetModel QmlObjectListModel(0x5a18b7491cd0) (QmlObjectListModelLog:unknown:0)
    40.305 - debug: _addMissionSettings (MissionControllerLog:unknown:0)
    40.305 - debug: First call to begindResetModel - calling QAbstractListModel::beginResetModel QmlObjectListModel(0x5a18bf2c4180) (QmlObjectListModelLog:unknown:0)
    40.305 - debug: _resetModelNestingCount: 1 QmlObjectListModel(0x5a18bf2c4180) (QmlObjectListModelLog:unknown:0)
    40.305 - debug: _resetModelNestingCount: 0 QmlObjectListModel(0x5a18bf2c4180) (QmlObjectListModelLog:unknown:0)
    40.305 - debug: Last call to endResetModel - calling QAbstractListModel::endResetModel QmlObjectListModel(0x5a18bf2c4180) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: setCurrentPlanViewSeqNum (MissionControllerLog:unknown:0)
    40.307 - debug: First call to begindResetModel - calling QAbstractListModel::beginResetModel QmlObjectListModel(0x5a18b8954b70) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _resetModelNestingCount: 1 QmlObjectListModel(0x5a18b8954b70) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _resetModelNestingCount: 0 QmlObjectListModel(0x5a18b8954b70) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: Last call to endResetModel - calling QAbstractListModel::endResetModel QmlObjectListModel(0x5a18b8954b70) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: First call to begindResetModel - calling QAbstractListModel::beginResetModel QmlObjectListModel(0x5a18b8954ba0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _resetModelNestingCount: 1 QmlObjectListModel(0x5a18b8954ba0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _resetModelNestingCount: 0 QmlObjectListModel(0x5a18b8954ba0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: Last call to endResetModel - calling QAbstractListModel::endResetModel QmlObjectListModel(0x5a18b8954ba0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: First call to begindResetModel - calling QAbstractListModel::beginResetModel QmlObjectListModel(0x5a18b8954cb0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _resetModelNestingCount: 1 QmlObjectListModel(0x5a18b8954cb0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _resetModelNestingCount: 0 QmlObjectListModel(0x5a18b8954cb0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: Last call to endResetModel - calling QAbstractListModel::endResetModel QmlObjectListModel(0x5a18b8954cb0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _activeVehicleChanged QObject(0x0) (PlanMasterControllerLog:unknown:0)
    40.307 - debug: setCurrentPlanViewSeqNum (MissionControllerLog:unknown:0)
    40.307 - debug: _activeVehicleChanged: Fly View - No active vehicle, clearing stale plan (PlanMasterControllerLog:unknown:0)
    40.307 - debug: First call to begindResetModel - calling QAbstractListModel::beginResetModel QmlObjectListModel(0x5a18bf44e9a0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _resetModelNestingCount: 1 QmlObjectListModel(0x5a18bf44e9a0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _resetModelNestingCount: 0 QmlObjectListModel(0x5a18bf44e9a0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: Last call to endResetModel - calling QAbstractListModel::endResetModel QmlObjectListModel(0x5a18bf44e9a0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _addMissionSettings (MissionControllerLog:unknown:0)
    40.307 - debug: First call to begindResetModel - calling QAbstractListModel::beginResetModel QmlObjectListModel(0x5a18bf2bbba0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _resetModelNestingCount: 1 QmlObjectListModel(0x5a18bf2bbba0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _resetModelNestingCount: 0 QmlObjectListModel(0x5a18bf2bbba0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: Last call to endResetModel - calling QAbstractListModel::endResetModel QmlObjectListModel(0x5a18bf2bbba0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: First call to begindResetModel - calling QAbstractListModel::beginResetModel QmlObjectListModel(0x5a18b870ce70) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _resetModelNestingCount: 1 QmlObjectListModel(0x5a18b870ce70) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _resetModelNestingCount: 0 QmlObjectListModel(0x5a18b870ce70) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: Last call to endResetModel - calling QAbstractListModel::endResetModel QmlObjectListModel(0x5a18b870ce70) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: First call to begindResetModel - calling QAbstractListModel::beginResetModel QmlObjectListModel(0x5a18b870cea0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _resetModelNestingCount: 1 QmlObjectListModel(0x5a18b870cea0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _resetModelNestingCount: 0 QmlObjectListModel(0x5a18b870cea0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: Last call to endResetModel - calling QAbstractListModel::endResetModel QmlObjectListModel(0x5a18b870cea0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: First call to begindResetModel - calling QAbstractListModel::beginResetModel QmlObjectListModel(0x5a18b870cfb0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _resetModelNestingCount: 1 QmlObjectListModel(0x5a18b870cfb0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: _resetModelNestingCount: 0 QmlObjectListModel(0x5a18b870cfb0) (QmlObjectListModelLog:unknown:0)
    40.307 - debug: Last call to endResetModel - calling QAbstractListModel::endResetModel QmlObjectListModel(0x5a18b870cfb0) (QmlObjectListModelLog:unknown:0)
Segmentation fault (core dumped)
</pre>`

**Comment by HTRamsey** [comment]
@DonLakeFlyer is this related to that removing links thing you fixed in daily?

Edit: oh actually nvm it's in the model resetting

**Comment by DonLakeFlyer** [comment]
I fixed this already in both stable and daily. I just haven't marked a new stable. @nathanvs-spsa Can you verify this is fixed in daily?

**Comment by DonLakeFlyer** [comment]
Here is a pointer to a new Stable 5.0 you can try: https://qgroundcontrol.s3.us-west-2.amazonaws.com/builds/Stable_V5.0/QGroundControl-x86_64.AppImage

**Comment by nathanvs-spsa** [comment]
> Here is a pointer to a new Stable 5.0 you can try: https://qgroundcontrol.s3.us-west-2.amazonaws.com/builds/Stable_V5.0/QGroundControl-x86_64.AppImage

Unfortunately the same issue still occurs on the above version @DonLakeFlyer  . Crash snippet attached.

[QGC_crash.txt](https://github.com/user-attachments/files/22608248/QGC_crash.txt)

**Comment by nathanvs-spsa** [comment]
Problem fixed in latest maser build - Closing as duplicate.
