### ISSUE TITLE
fullscreen issue in android device

### ISSUE THREAD

**Issue by hyeonseung89** [mavlink/qgroundcontrol#13550]
### Have you checked the latest release for fixes?

- [x] Yes, I’ve tested on the latest release

### Description

**Expected Behavior**
I expect the app to display in full screen when launched on Android device. 

**Current Behavior**
However, even though the top bar and bottom toolbar have disappeared, the space they occupied still remains, so the app is not displayed in full screen. This was working normally in version 6.8.3, but the issue appeared after updating to version 6.10. I would like to request the developers to review this.

**Steps To Reproduce**
1. launch app

**Additional Details**
stable version 5.0.8

![Image](https://github.com/user-attachments/assets/1038cfc9-dfb4-44e2-8006-af1b93b3fdf5)

master version
![Image](https://github.com/user-attachments/assets/6f370265-1c52-4a7e-bf63-d21b8e376325)

### System Information

latest qgc master version compiled in action

**Comment by DonLakeFlyer** [comment]
I've noticed the same thing on my UniRC7 controller.

**Comment by superizer** [comment]
I've faced the same thing on my skydroid G20

**Comment by aryan-9760** [comment]
@DonLakeFlyer i have had the same issue on a SIYI MK15 screen. i believe this is the cause for it, i have fixed it on my fork. 

Root cause: Three things were preventing the app from using the full screen:

  1. No immersive fullscreen mode — The Android status bar (top) and navigation bar (right side in landscape) were reserving screen space. QGCActivity.java never requested immersive mode, so the system bars   consumed screen real estate even though the QML layout filled its window correctly.
  2. Android theme was disabled — AndroidManifest.xml had android:theme="@style/AppTheme" commented out, so all theme settings in apptheme.xml (bar colors, fullscreen flags) had no effect.
  3. No display cutout handling — Without FLAG_LAYOUT_NO_LIMITS and LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES, Android reserved layout space for the navigation bar area even when the bar was hidden. 
       
  Fix (3 files):

  - QGCActivity.java — Added enableImmersiveMode() using WindowInsetsController (API 30+) with SYSTEM_UI_FLAG_IMMERSIVE_STICKY fallback for older devices. Also added FLAG_LAYOUT_NO_LIMITS and
  LAYOUT_IN_DISPLAY_CUTOUT_MODE_SHORT_EDGES to extend into all reserved areas. Re-applied on onWindowFocusChanged() to persist across focus changes.
  - apptheme.xml — Changed parent theme to Theme.DeviceDefault.NoActionBar, set transparent status/navigation bars, black window background, and windowLayoutInDisplayCutoutMode=shortEdges.
  - AndroidManifest.xml — Uncommented android:theme="@style/AppTheme" to actually apply the theme.

**Comment by HTRamsey** [comment]
Was this still an issue for you on master? We applied a fix to the ApplicationWindow that was supposed to resolve this

**Comment by DonLakeFlyer** [comment]
Closing since no response. This should be fixed
