### ISSUE TITLE
Tuning tab hangs disconnects and reconnects

### ISSUE THREAD

**Issue by jcooper21** [mavlink/qgroundcontrol#3290]
The tuning tab seems to hand in QGC 2.9.4 with stable built. It's disconnects and reconnects then loads the page. switching airframes seems to hang as well.

Sensor setup is brutal it's almost too buggy to be usable.

**Comment by jcooper21** [comment]
heres a screenshot of how bad it is.  This is just compass bur all of the sensors are just as bad.
![capture](https://cloud.githubusercontent.com/assets/14355782/14869739/b57bbae2-0c92-11e6-93ed-42f9aad62bf6.PNG)

**Comment by LorenzMeier** [comment]
@jcooper21 Do you have wireless and USB connected at the same time?

**Comment by jcooper21** [comment]
No sir this is only over 915mhz telemetry. This is a picture of what was discussed on the px4 beta 1.3 support page today.

**Comment by LorenzMeier** [comment]
Got it. Calibration via radio won't work reliably. Please use a USB cable for now.

**Comment by jcooper21** [comment]
That will be a bit of a challenge but will do. Thank you.

**Comment by dogmaphobic** [comment]
I get lost in this as there seems to be way too many places where this is being discussed. The problem @jcooper21 described in http://discuss.px4.io/t/v1-3-0-beta-testing/283/77 sounds an awful lot like missing (lost) messages during the calibration. QGC doesn't handle well data loss during calibration (if at all). So much so that if you try to do it using UDP, it will tell you so. It just missed the fact you were using a radio modem (I guess it only checks to see if it sees the connection as UDP).

**Comment by jcooper21** [comment]
I would like to suggest having a note in the sensor setup page saying calibrate only with usb plugged in.

**Comment by DonLakeFlyer** [comment]
That is already in the daily build? Is it not working?

**Comment by jcooper21** [comment]
Which part is supposed to be in there?

**Comment by DonLakeFlyer** [comment]
QGC will warn if you try to calibrate over a UDP connection.

**Comment by jcooper21** [comment]
Not sure I was referring to 900 MHz not udp. I think Lorenz mode the calibration better the other day.

**Comment by DonLakeFlyer** [comment]
Ah, thought this was UDP. Is this problem fixed now then?

**Comment by jcooper21** [comment]
It seems improved as far as I can tell but he would be best to speak with.

**Comment by dogmaphobic** [comment]
In addition to all of the above, UDP (using the ESP WiFi Module) is handling data loss a lot better. I got it down to almost no loss (though some do still get dropped, it's lets than 0.5%). I have yet to test calibration though as it's not simple to calibrate a pile of wires with no actual frame :)
