### ISSUE TITLE
Ubuntu 16.04 segfault at launch

### ISSUE THREAD

**Issue by jaxxzer** [mavlink/qgroundcontrol#4688]
The application segfaults at launch on Ubuntu 16.04, since switch to 5.8.

**Comment by jaxxzer** [comment]
Tested with precompiled daily build, and compiling natively from source using QT 5.8. Compiling the same tree using QT 5.5.1 does not segfault.

**Comment by jaxxzer** [comment]
Same problems on QT 5.7...

**Comment by DonLakeFlyer** [comment]
I'm assuming you built yourself? Daily build drops are still on 5.8.

**Comment by jaxxzer** [comment]
Yes, regarding 5.7 I built myself.

**Comment by dagar** [comment]
@jaxxzer is this the appimage, tarball, or running straight out of Qtcreator?

**Comment by jaxxzer** [comment]
AppImage, and QTCreator.

**Comment by hbrezak** [comment]
I'm running Ubuntu 14.04 and tried DailyBuild from official site, both Linux AppImage and Compressed archive. Both cases result in segmentation fault. Leading up to seg fault:

`Settings location "/home/hrvoje/.config/QGroundControl.org/QGroundControl.ini" Is writable?: true
Filter rules "qt.network.ssl.warning=false\n*Log.debug=false\n"
MAVLinkLogManagerLog: MAVLink logs directory: "/home/hrvoje/.local/share/QGroundControl.org/QGroundControl/MAVLinkLogs"
Map Cache in: "/home/hrvoje/.cache/QGCMapCache300" / "qgcMapCache.db"
Segmentation fault (core dumped)`

**Comment by NaterGator** [comment]
@DonLakeFlyer what about those QtLocation private headers we have mirrored in the QtLocationPlugin? I don't think they've been updated to match our current version of Qt and should be scrutinized as a possible source of problems here.

**Comment by dogmaphobic** [comment]
Those are only used for Qt 5.5.1. For all other versions, the normal (distribution) path is used.

**Comment by DonLakeFlyer** [comment]
I built on 14.04 with Qt 5.7 and everything works ok. Need to switch build system to 5.7

**Comment by DonLakeFlyer** [comment]
Fixed and tested daily build AppImage on both 14 and 16 ubuntu. No more crash. Although gstreamer doesn't seem to work on either. I'll enter a seperate issue for that.

**Comment by jaxxzer** [comment]
Still getting a segfault on daily build 16.04, gstreamer has been uninstalled.

```
$ ./QGroundControl.AppImage
Settings location "/home/jack/.config/QGroundControl.org/QGroundControl.ini" Is writable?: true
Filter rules "qt.network.ssl.warning=false\n*Log.debug=false\n"
MAVLinkLogManagerLog: MAVLink logs directory: "/home/jack/.local/share/QGroundControl.org/QGroundControl/MAVLinkLogs"
Map Cache in: "/home/jack/.cache/QGCMapCache300" / "qgcMapCache.db"
Orphaned log file count 0
LinkManager mavlinkStatus:channel:flags 0xfc4b48 1 2
Segmentation fault (core dumped)
```

**Comment by DonLakeFlyer** [comment]
@jaxxzer I can't seem to repro this. If you can repro on something you build yourself can you get it in a debugger and take a look?

**Comment by jaxxzer** [comment]
I get a segfault at launch 19/20 times (Ubuntu 16.04 only), sometimes it will launch ok.

Here is a stack trace, always the same, everything but the top level call to app->exec() is disassembly, so I'm not sure where to go from here in troubleshooting the issue.

![screenshot 2017-03-24 15 42 25](https://cloud.githubusercontent.com/assets/8315108/24314783/ca11775e-10b9-11e7-806f-8ddd618d6877.png)


Here is a log with --logging:full set.


[qgclog.txt](https://github.com/mavlink/qgroundcontrol/files/869286/qgclog.txt)

**Comment by DonLakeFlyer** [comment]
That looks like and OpenGL driver bug.

On Mar 24, 2017, at 2:46 PM, jaxxzer <notifications@github.com<mailto:notifications@github.com>> wrote:


I get a segfault at launch 19/20 times (Ubuntu 16.04 only), sometimes it will launch ok.

Here is a stack trace, always the same, everything but the top level call to app->exec() is disassembly, so I'm not sure where to go from here in troubleshooting the issue.

[screenshot 2017-03-24 15 42 25]<https://cloud.githubusercontent.com/assets/8315108/24314783/ca11775e-10b9-11e7-806f-8ddd618d6877.png>

Here is a log with --logging:full set.

qgclog.txt<https://github.com/mavlink/qgroundcontrol/files/869286/qgclog.txt>

**Comment by jaxxzer** [comment]
I have a third-party (AMD Radeon) graphics driver on this machine, do you think that could be the part of the issue? 

Interestingly, the application always starts (slowly) with valgrind memory analyzer. So looks like a race is going on.

**Comment by DonLakeFlyer** [comment]
Windows has similar problems with bad OpenGL drivers. 

@NaterGator What's the thing to tell QGC to use software rendering instead? Is that available in Linux as well?

**Comment by jaxxzer** [comment]
Working for me now on master, haven't touched the QT installation...

**Comment by DonLakeFlyer** [comment]
I'm just guessing flaky opengl driver + QGC ui moving around making different Qml calls. Closing for now to see if it comes back,

**Comment by jaxxzer** [comment]
This is a problem with my graphics driver. @NaterGator is software rendering available on Linux?

**Comment by DonLakeFlyer** [comment]
If you look in main.cc you'll see ifdef Q_OS_WIN code for -angle and -swrast? You should build your own and see if it works for you.
