### ISSUE TITLE
ArduPilot: Support to flash MindPx-v2 boards

### ISSUE THREAD

**Issue by lvale** [mavlink/qgroundcontrol#6786]
Hi @DonLakeFlyer 

As we've discussed, one of the supported boards on the new chibios releases are the MindPx

example for plane:
http://firmware.ardupilot.org/Plane/stable/mindpx-v2/

These are only supported for this release of plane and rover and on betas/master of the other vehicles copter and heli

**Comment by DonLakeFlyer** [comment]
@lvale With latest daily this is fixed now right?

**Comment by lvale** [comment]
Recognises the board for regular setting up and flight.

Flashing still broken

<img width="746" alt="screenshot 2018-11-29 at 02 16 29" src="https://user-images.githubusercontent.com/3130363/49194916-e77ca500-f37c-11e8-87a3-18c2bfd3b2d8.png">


Tangentially related. fmuv5 (CUAV v5) is flashing ok

**Comment by lvale** [comment]
Sure

[firmwarefailed.txt](https://github.com/mavlink/qgroundcontrol/files/2627377/firmwarefailed.txt)
