### ISSUE TITLE
new mission line bisector not working right with Landing Pattern (and other complex patterns?)

### ISSUE THREAD

**Issue by Antiheavy** [mavlink/qgroundcontrol#7792]
If the Landing Pattern is active, and I click on the line bisector running to the Loiter, a line is created from the Land WP to the bisector.  I'm pretty sure this is not intended.
![image](https://user-images.githubusercontent.com/12117027/64490931-eb045d00-d227-11e9-8f3d-22787766a45c.png)

and when I delete the landing pattern, these lines show up as orphaned items:
![image](https://user-images.githubusercontent.com/12117027/64490944-15eeb100-d228-11e9-8c50-3a9e5c81dfaf.png)

and then trying to place a new landing pattern doesn't work, but weird artifacts show up if I keep clicking:
![image](https://user-images.githubusercontent.com/12117027/64490985-5c441000-d228-11e9-928f-556e92bf7ef5.png)

**Comment by DonLakeFlyer** [comment]
Are you using a master from last night. I fixed a bunch of stuff around this yesterday. I tried the bisect while Landing pattern selected and it worked fine for me.

**Comment by Antiheavy** [comment]
Still happening for me on today's daily (different laptop this time):
![image](https://user-images.githubusercontent.com/12117027/64550824-5407d580-d2f9-11e9-8f2b-f845826dc254.png)

**Comment by DonLakeFlyer** [comment]
Ah, sorry. It's the Survey item which is making this crap out. I thought it was just the Landing pattern. I can reproduce.

**Comment by Antiheavy** [comment]
yep.  fixed.  thanks.
